version: '2'

services:

  dashboard:
    container_name: dashboard
    image: registry.npd.learndirect.com/dashboard:master
    build:
      context: .
      args:
        - http_proxy
        - https_proxy



