version: '2'

services:

  ansible:
    container_name: ansible
    image: "ansible"
    build: .
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./out:/etc/ansible/conf.d
#      - ./files/ansible.conf:/etc/ansible/ansible.conf:ro
#    networks:
#      - repo-net
#    restart: always

#  nexus:
#    container_name: nexus
#    ports:
#      - 8081:8081
#      - 127.0.0.1:5000:5000
#    build:
#      context: nexus/.
#      args:
#        - http_proxy
#        - https_proxy
##    environment:
##      - VIRTUAL_HOST=nexus.npd.learndirect.com
#    volumes:
#      - nexus-data:/nexus-data
#    networks:
#      - repo-net
#    restart: always
